[tool.ruff]
target-version = "py312"
line-length = 88
src = ["src", "app", "."]

exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "migrations",
]

[tool.ruff.lint]

select = [
    "F",    # erreurs Python (flake8 F)
    "E",    # style / erreurs flake8
    "W",    # warnings flake8
    "I",    # import (isort-like)  
    "N",
    "B",    # bugbear
    "UP",   # upgrades (pyupgrade)
    "SIM",  # simplifications
    "C4",
    "PERF",
    "ARG",  # arguments inutilisés
    "DTZ",  # timezone
    "S",    # sécurité
    "ANN",  # typing / annotations
]



ignore = [
    "E203",
    "E501",
    "W293"  ,  # blank line contains whitespace
]


[tool.ruff.format]
line-ending = "lf"
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
